config/routes.rb
Rails.application.routes.draw do

  resources :serverhascontainers
  resources :servertags
  resources :containertags
  resources :tags
  devise_for :users
	resources :containers
	root 'home#index'
	resources :servers
	get '/containers/:id/start', to: 'containers#start', as: 'start_container'
	get '/containers/:id/stop', to: 'containers#stop', as: 'stop_container'
	get '/containers/:id/pause', to: 'containers#pause'
	get '/containers/:id/unpause', to: 'containers#unpause'
	get '/containers/new/:id', to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/container.rb
class Container < ApplicationRecord
	has_many :containertags
	has_many :tags, :through => :containertags
	has_many :serverhascontainers
	has_many :servers, :through => :serverhascontainers

	attr_accessor :server_id
	
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController

  #workaround to use NO AUTHENTICATION - UNSAFE
  skip_before_filter :verify_authenticity_token

  before_action :set_container, only: [:show, :edit, :update, :destroy, :start, :stop, :pause, :unpause]
  

  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
  end

  # GET /containers/new
  def new
    @container = Container.new
  end

  # GET /containers/1/edit
  def edit
  end

  # POST /containers
  # POST /containers.json

  def create
    begin
      #get the server chosen container_params[:server_id]
      @currentServer = Server.where(id: container_params[:server_id])
      Docker.url = 'tcp://' + @currentServer[0].ip + ":" + @currentServer[0].port

      #create the container in docker
      if container_params[:exposed_port].blank?
        @con = Docker::Container.create(
        'name' => container_params[:name],
        'Image' => container_params[:image]
        )      
      else 
        @con = Docker::Container.create(
        'name' => container_params[:name],
        'Image' => container_params[:image],
        'ExposedPorts' => { container_params[:exposed_port]+'/tcp' => {} },
        'HostConfig' => {
          'PortBindings' => {
            container_params[:exposed_port]+'/tcp' => [{ 'HostPort' => container_params[:host_port] }]
          }
        }
      )
      end

      #adds the container into the database
      @container = Container.new(:name => container_params[:name], :image => container_params[:image], :command => container_params[:command], :exposed_port => container_params[:exposed_port], 
        :host_port => container_params[:host_port], :dockercontainer_id => @con.id, :status => 'Created')

      Docker.url = ''

      respond_to do |format|
        if @container.save
          Serverhascontainer.new(:server_id => @currentServer[0].id, :container_id => @container.id).save
          format.html { redirect_to root_path, notice: 'Container was successfully created.' }
          format.json { render :show, status: :created, location: @container }
        else
          format.html { render :new }
          format.json { render json: @container.errors, status: :unprocessable_entity }
        end
      end

    rescue Docker::Error::ClientError => e
      respond_to do |format| 
        format.html { redirect_to root_path, notice: "Oops: #{e.message}" }
      end

    rescue Docker::Error::NotFoundError => e
      respond_to do |format| 
        format.html { redirect_to root_path, notice: "Oops: #{e.message}" }
      end

    rescue Docker::Error::ConflictError => e
      respond_to do |format| 
        format.html { redirect_to root_path, notice: "Oops: #{e.message}" }
      end

    end
  end

  # PATCH/PUT /containers/1
  # PATCH/PUT /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    begin
      #finds the current server that the container is on and sets it as Docker.ulr
      #@serverid = Serverhascontainer.where(container_id: @container.id)[0].server_id;
      #@currentServer = Server.where(id: @serverid)
      #Docker.url = 'tcp://' + @currentServer[0]["ip"] + ":" + @currentServer[0]["port"]
      Docker.url = findServer()

      #removes the container from docker
      Docker::Container.get(Container.find(params[:id]).dockercontainer_id).remove;

      #removes the Server-container relation from the database
      @d = Serverhascontainer.where(container_id: @container.id)        
      Serverhascontainer.destroy(@d[0].id);

      #removes the container from the database
      @container.destroy
      Docker.url = ''
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'deleted.' }
        format.json { head :no_content }
      end

    rescue Docker::Error::ConflictError => e
      respond_to do |format| 
        format.html { redirect_to root_path, notice: "Oops: You cannot remove a running container. Stop the container before attempting removal" }
      end
    end
  end

  def start
    #@serverid = Serverhascontainer.where(container_id: @container.id)[0].server_id;
    #@currentServer = Server.where(id: @serverid)
    #Docker.url = 'tcp://' + @currentServer[0]["ip"] + ":" + @currentServer[0]["port"]
    Docker.url = findServer()

    Docker::Container.get(Container.find(params[:id]).dockercontainer_id).start;
    @container.update(:status => 'running')
    Docker.url = ''
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Container was started.' }
    end

  end

  def stop
    #@serverid = Serverhascontainer.where(container_id: @container.id)[0].server_id;
    #@currentServer = Server.where(id: @serverid)
    #Docker.url = 'tcp://' + @currentServer[0]["ip"] + ":" + @currentServer[0]["port"]
    Docker.url = findServer()
    Docker::Container.get(Container.find(params[:id]).dockercontainer_id).stop;
    @container.update(:status => 'exited')
    Docker.url = ''
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Container was stopped.' }
    end
  end

  def pause
    #@serverid = Serverhascontainer.where(container_id: @container.id)[0].server_id;
    #@currentServer = Server.where(id: @serverid)
    #Docker.url = 'tcp://' + @currentServer[0]["ip"] + ":" + @currentServer[0]["port"]
    Docker.url = findServer()

    Docker::Container.get(Container.find(params[:id]).dockercontainer_id).pause;
    @container.update(:status => 'paused')
    Docker.url = ''
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Container was paused.' }
    end
  end

  def unpause
    #@serverid = Serverhascontainer.where(container_id: @container.id)[0].server_id;
    #@currentServer = Server.where(id: @serverid)
    #Docker.url = 'tcp://' + @currentServer[0]["ip"] + ":" + @currentServer[0]["port"]
    Docker.url = findServer()
    
    Docker::Container.get(Container.find(params[:id]).dockercontainer_id).unpause;
    @container.update(:status => 'running')
    Docker.url = ''
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Container was unpaused.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    #fungerar inte atm
    def findServer
      @serverid = Serverhascontainer.where(container_id: @container.id)[0].server_id;
      @currentServer = Server.where(id: @serverid)
      @c = 'tcp://' + @currentServer[0]["ip"] + ":" + @currentServer[0]["port"]
      return @c;
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params.require(:container).permit(:name, :image, :command, :exposed_port, :host_port, :server_id)
    end
  end

app/views/containers/_form.html.erb
<%= form_for(container) do |f| %>
<% if container.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(container.errors.count, "error") %> prohibited this container from being saved:</h2>

  <ul>
    <% container.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>



<div class="form-inputs">
  <div class="form-group has-success has-feedback">
    <%= f.label :name, class: "sr-only" %>
    <%= f.text_field(:name, class: "form-control", placeholder: "Name") %>
  </div>

  <div class="form-group has-success has-feedback">
    <%= f.label :image, class: "sr-only" %>
    <%= f.text_field(:image, class: "form-control", placeholder: "Image") %>
  </div>

  <div class="form-group has-success has-feedback">
    <%= f.label :command, class: "sr-only" %>
    <%= f.text_field(:command, class: "form-control", placeholder: "Command") %>
  </div>

  <div class="form-group has-success has-feedback">
    <%= f.label :exposed_port, class: "sr-only" %>
    <%= f.text_field(:exposed_port, class: "form-control", placeholder: "Exposed Port") %>
  </div>

  <div class="form-group has-success has-feedback">
    <%= f.label :host_port, class: "sr-only" %>
    <%= f.text_field(:host_port, class: "form-control", placeholder: "Host Port") %>
  </div>

  <div class="form-group has-success has-feedback">
    <%= f.label :server_id, class: "sr-only" %>
    <%= f.collection_select :server_id, @servers ,:id,:name, {}, {:class => 'form-control'} %>
  </div>

  <div class="actions">
    <%= f.submit(class: "btn btn-default") %>
    <button type="button" class="btn btn-default right" data-dismiss="modal">Close</button>
  </div>



</div>



<% end %>

app/views/containers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Containers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Container</th>
      <th>Image</th>
      <th>Command</th>
      <th>Status</th>
      <th>Exposed port</th>
      <th>Host port</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @containers.each do |container| %>
      <tr>
        <td><%= container.name %></td>
        <td><%= container.dockercontainer_id %></td>
        <td><%= container.image %></td>
        <td><%= container.command %></td>
        <td><%= container.status %></td>
        <td><%= container.exposed_port %></td>
        <td><%= container.host_port %></td>
        <td><%= link_to 'Show', container %></td>
        <td><%= link_to 'Edit', edit_container_path(container) %></td>
        <td><%= link_to 'Destroy', container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Container', new_container_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @container.name %>
</p>

<p>
  <strong>Container:</strong>
  <%= @container.dockercontainer_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @container.image %>
</p>

<p>
  <strong>Command:</strong>
  <%= @container.command %>
</p>

<p>
  <strong>Status:</strong>
  <%= @container.status %>
</p>

<p>
  <strong>Exposed port:</strong>
  <%= @container.exposed_port %>
</p>

<p>
  <strong>Host port:</strong>
  <%= @container.host_port %>
</p>

<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>