config/routes.rb
Rails.application.routes.draw do

  resources :serverhascontainers
  resources :servertags
  resources :containertags
  resources :tags
  devise_for :users
	resources :containers
	root 'home#index'
	resources :servers
	get '/containers/:id/start', to: 'containers#start', as: 'start_container'
	get '/containers/:id/stop', to: 'containers#stop', as: 'stop_container'
	get '/containers/:id/pause', to: 'containers#pause'
	get '/containers/:id/unpause', to: 'containers#unpause'
	get '/containers/new/:id', to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/containertag.rb
class Containertag < ApplicationRecord
  belongs_to :container
  belongs_to :tag
end

app/controllers/containertags_controller.rb
class ContainertagsController < ApplicationController
  before_action :set_containertag, only: [:show, :edit, :update, :destroy]

  # GET /containertags
  # GET /containertags.json
  def index
    @containertags = Containertag.all
  end

  # GET /containertags/1
  # GET /containertags/1.json
  def show
  end

  # GET /containertags/new
  def new
    @containertag = Containertag.new
  end

  # GET /containertags/1/edit
  def edit
  end

  # POST /containertags
  # POST /containertags.json
  def create
    @containertag = Containertag.new(containertag_params)

    respond_to do |format|
      if @containertag.save
        format.html { redirect_to @containertag, notice: 'Containertag was successfully created.' }
        format.json { render :show, status: :created, location: @containertag }
      else
        format.html { render :new }
        format.json { render json: @containertag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containertags/1
  # PATCH/PUT /containertags/1.json
  def update
    respond_to do |format|
      if @containertag.update(containertag_params)
        format.html { redirect_to @containertag, notice: 'Containertag was successfully updated.' }
        format.json { render :show, status: :ok, location: @containertag }
      else
        format.html { render :edit }
        format.json { render json: @containertag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containertags/1
  # DELETE /containertags/1.json
  def destroy
    @containertag.destroy
    respond_to do |format|
      format.html { redirect_to containertags_url, notice: 'Containertag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_containertag
      @containertag = Containertag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def containertag_params
      params.require(:containertag).permit(:container_id, :tag_id)
    end
end

app/helpers/containertags_helper.rb
module ContainertagsHelper
end

app/views/containertags/_form.html.erb
<%= form_for(containertag) do |f| %>
  <% if containertag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(containertag.errors.count, "error") %> prohibited this containertag from being saved:</h2>

      <ul>
      <% containertag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :container_id %>
    <%= f.text_field :container_id %>
  </div>

  <div class="field">
    <%= f.label :tag_id %>
    <%= f.text_field :tag_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containertags/edit.html.erb
<h1>Editing Containertag</h1>

<%= render 'form', containertag: @containertag %>

<%= link_to 'Show', @containertag %> |
<%= link_to 'Back', containertags_path %>

app/views/containertags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Containertags</h1>

<table>
  <thead>
    <tr>
      <th>Container</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @containertags.each do |containertag| %>
      <tr>
        <td><%= containertag.container %></td>
        <td><%= containertag.tag %></td>
        <td><%= link_to 'Show', containertag %></td>
        <td><%= link_to 'Edit', edit_containertag_path(containertag) %></td>
        <td><%= link_to 'Destroy', containertag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Containertag', new_containertag_path %>

app/views/containertags/new.html.erb
<h1>New Containertag</h1>

<%= render 'form', containertag: @containertag %>

<%= link_to 'Back', containertags_path %>

app/views/containertags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Container:</strong>
  <%= @containertag.container %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @containertag.tag %>
</p>

<%= link_to 'Edit', edit_containertag_path(@containertag) %> |
<%= link_to 'Back', containertags_path %>